In [1]:
# 1.Create two NumPy arrays representing the daily step counts of two friends over a week and use element-wise addition, subtraction, multiplication, and division to compare their activity levels.
import numpy as np

friend1 = np.array([5000, 6000, 7500, 8000, 9000, 7000, 8500])
friend2 = np.array([4500, 6500, 7000, 8500, 8000, 7500, 9000])

# Element-wise operations
addition = friend1 + friend2
subtraction = friend1 - friend2
multiplication = friend1 * friend2
division = friend1 / friend2

print("Friend 1:", friend1)
print("Friend 2:", friend2)

print("\nAddition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

Friend 1: [5000 6000 7500 8000 9000 7000 8500]
Friend 2: [4500 6500 7000 8500 8000 7500 9000]

Addition: [ 9500 12500 14500 16500 17000 14500 17500]
Subtraction: [ 500 -500  500 -500 1000 -500 -500]
Multiplication: [22500000 39000000 52500000 68000000 72000000 52500000 76500000]
Division: [1.11111111 0.92307692 1.07142857 0.94117647 1.125      0.93333333
 0.94444444]


In [2]:
# 2.Simulate a Spotify-like 'Recommended Songs' feature: Given two 3x3 matrices representing user-song interaction scores (user preferences and song popularity), use dot() and matmul() to compute the final recommendation matrix and explain the difference between the two results.
import numpy as np

user_preferences = np.array([
    [5, 4, 3],
    [2, 5, 4],
    [4, 3, 5]
])

song_popularity = np.array([
    [5, 2, 1],
    [3, 5, 2],
    [1, 3, 5]
])

# Matrix multiplication using dot()
recommendation_dot = np.dot(user_preferences, song_popularity)

# Matrix multiplication using matmul()
recommendation_matmul = np.matmul(user_preferences, song_popularity)

print("Using dot():")
print(recommendation_dot)

print("\nUsing matmul():")
print(recommendation_matmul)

Using dot():
[[40 39 28]
 [29 41 32]
 [34 38 35]]

Using matmul():
[[40 39 28]
 [29 41 32]
 [34 38 35]]


In [3]:
# 3.Given a 4x4 NumPy matrix representing the pixel brightness of a small Instagram image, use transpose (T) to rotate the image and then calculate the mean, median, standard deviation, and variance of the pixel values.
import numpy as np

image = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

# Transpose the matrix
rotated_image = image.T

print("Original image:")
print(image)

print("\nTransposed image:")
print(rotated_image)

print("\nMean:", np.mean(image))
print("Median:", np.median(image))
print("Standard deviation:", np.std(image))
print("Variance:", np.var(image))

Original image:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]

Transposed image:
[[ 10  50  90 130]
 [ 20  60 100 140]
 [ 30  70 110 150]
 [ 40  80 120 160]]

Mean: 85.0
Median: 85.0
Standard deviation: 46.09772228646444
Variance: 2125.0


In [4]:
# 4.Take a 3x3 NumPy matrix representing a Zomato restaurant rating correlation grid and use np.linalg.inv(), np.linalg.det(), and np.linalg.eig() to compute its inverse, determinant, and eigenvalues/eigenvectors.<br><br><em><strong>Hint:</strong> If the matrix is not invertible, modify one value and try again.</em>
import numpy as np

ratings = np.array([
    [2, 1, 0],
    [1, 3, 1],
    [0, 1, 2]
], dtype=float)

# Inverse
inverse = np.linalg.inv(ratings)

# Determinant
determinant = np.linalg.det(ratings)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(ratings)

print("Matrix:")
print(ratings)

print("\nInverse:")
print(inverse)

print("\nDeterminant:")
print(determinant)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Matrix:
[[2. 1. 0.]
 [1. 3. 1.]
 [0. 1. 2.]]

Inverse:
[[ 0.625 -0.25   0.125]
 [-0.25   0.5   -0.25 ]
 [ 0.125 -0.25   0.625]]

Determinant:
8.000000000000002

Eigenvalues:
[4.+0.j 2.+0.j 1.+0.j]

Eigenvectors:
[[-4.08248290e-01+0.j  7.07106781e-01+0.j  5.77350269e-01+0.j]
 [-8.16496581e-01+0.j -3.45742585e-16+0.j -5.77350269e-01+0.j]
 [-4.08248290e-01+0.j -7.07106781e-01+0.j  5.77350269e-01+0.j]]


In [5]:
# 5.Create a NumPy array of shape (2, 6) representing the number of orders placed on Swiggy in two cities over 6 days. Reshape it to (3, 4), flatten it, split it into two equal parts, and then stack both parts vertically.
import numpy as np

orders = np.array([
    [10, 20, 15, 25, 30, 18],
    [12, 22, 17, 27, 32, 20]
])

print("Original array:")
print(orders)

# Reshape from (2, 6) to (3, 4)
reshaped = orders.reshape(3, 4)

print("\nReshaped array:")
print(reshaped)

# Flatten the array
flattened = reshaped.flatten()

print("\nFlattened array:")
print(flattened)

# Split into two equal parts
part1, part2 = np.split(flattened, 2)

print("\nPart 1:")
print(part1)

print("\nPart 2:")
print(part2)

# Stack both parts vertically
stacked = np.vstack((part1, part2))

print("\nVertically stacked:")
print(stacked)

Original array:
[[10 20 15 25 30 18]
 [12 22 17 27 32 20]]

Reshaped array:
[[10 20 15 25]
 [30 18 12 22]
 [17 27 32 20]]

Flattened array:
[10 20 15 25 30 18 12 22 17 27 32 20]

Part 1:
[10 20 15 25 30 18]

Part 2:
[12 22 17 27 32 20]

Vertically stacked:
[[10 20 15 25 30 18]
 [12 22 17 27 32 20]]
