In [1]:
# 1.Create a 2D NumPy array representing the ratings (out of 5) given by 4 users to 5 different food items on Zomato. Use slicing to extract the ratings given by the second and third users only.
import numpy as np

ratings = np.array([
    [4, 5, 3, 4, 5],
    [5, 4, 4, 3, 5],
    [3, 5, 4, 4, 3],
    [4, 3, 5, 5, 4]
])

# Extract second and third users
selected_ratings = ratings[1:3]

print("Ratings:")
print(ratings)

print("\nRatings of second and third users:")
print(selected_ratings)

Ratings:
[[4 5 3 4 5]
 [5 4 4 3 5]
 [3 5 4 4 3]
 [4 3 5 5 4]]

Ratings of second and third users:
[[5 4 4 3 5]
 [3 5 4 4 3]]


In [2]:
# 2.Given a NumPy array of daily steps tracked for 10 days, use boolean indexing to select only the days where the steps were greater than 8000.<br><br><em><strong>Hint:</strong> Use an array like steps = np.array([7500, 8200, 9000, ...]) and apply a boolean condition.</em>
import numpy as np

steps = np.array([7500, 8200, 9000, 6500, 10000, 7800, 8500, 7200, 9200, 6000])

# Select steps greater than 8000
high_steps = steps[steps > 8000]

print("Steps greater than 8000:")
print(high_steps)

Steps greater than 8000:
[ 8200  9000 10000  8500  9200]


In [3]:
# 3.Create a NumPy array of IPL team scores for 8 matches. Use fancy indexing to select the scores from matches 2, 5, and 7, and print them.
import numpy as np

scores = np.array([185, 210, 165, 192, 225, 178, 205, 190])

# Matches 2, 5 and 7
selected_scores = scores[[1, 4, 6]]

print("IPL scores:")
print(scores)

print("\nScores from matches 2, 5 and 7:")
print(selected_scores)

IPL scores:
[185 210 165 192 225 178 205 190]

Scores from matches 2, 5 and 7:
[210 225 205]


In [4]:
# 4.Suppose you have a NumPy array of product prices from Flipkart. Use broadcasting to apply a 10% discount to all prices and print the new array.<br><br><em><strong>Constraint:</strong> Do not use any loops.</em>
import numpy as np

prices = np.array([1000, 2000, 1500, 3000, 2500])

# Apply 10% discount
discounted_prices = prices * 0.90

print("Original prices:")
print(prices)

print("\nPrices after 10% discount:")
print(discounted_prices)

Original prices:
[1000 2000 1500 3000 2500]

Prices after 10% discount:
[ 900. 1800. 1350. 2700. 2250.]


In [5]:
# 5.Given a NumPy array of user ratings (can be negative, zero, or positive) for songs on Spotify, use boolean masking to set all negative ratings to zero, keeping other ratings unchanged.
import numpy as np

ratings = np.array([-2, 5, 3, -1, 0, 4, -3, 5])

# Set negative ratings to zero
ratings[ratings < 0] = 0

print("Ratings after replacing negative values:")
print(ratings)

Ratings after replacing negative values:
[0 5 3 0 0 4 0 5]
